//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EV3_Control.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99")]
        public int U_B_ControlSpeed_UP {
            get {
                return ((int)(this["U_B_ControlSpeed_UP"]));
            }
            set {
                this["U_B_ControlSpeed_UP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99")]
        public int U_B_ControlSpeed_DOWN {
            get {
                return ((int)(this["U_B_ControlSpeed_DOWN"]));
            }
            set {
                this["U_B_ControlSpeed_DOWN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99")]
        public int U_B_ControlSpeed_LEFT {
            get {
                return ((int)(this["U_B_ControlSpeed_LEFT"]));
            }
            set {
                this["U_B_ControlSpeed_LEFT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99")]
        public int U_B_ControlSpeed_RIGHT {
            get {
                return ((int)(this["U_B_ControlSpeed_RIGHT"]));
            }
            set {
                this["U_B_ControlSpeed_RIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool U_B_Control_UP_A {
            get {
                return ((bool)(this["U_B_Control_UP_A"]));
            }
            set {
                this["U_B_Control_UP_A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool U_B_Control_UP_B {
            get {
                return ((bool)(this["U_B_Control_UP_B"]));
            }
            set {
                this["U_B_Control_UP_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool U_B_Control_UP_C {
            get {
                return ((bool)(this["U_B_Control_UP_C"]));
            }
            set {
                this["U_B_Control_UP_C"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool U_B_Control_UP_D {
            get {
                return ((bool)(this["U_B_Control_UP_D"]));
            }
            set {
                this["U_B_Control_UP_D"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool U_B_Control_DOWN_A {
            get {
                return ((bool)(this["U_B_Control_DOWN_A"]));
            }
            set {
                this["U_B_Control_DOWN_A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool U_B_Control_DOWN_B {
            get {
                return ((bool)(this["U_B_Control_DOWN_B"]));
            }
            set {
                this["U_B_Control_DOWN_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool U_B_Control_DOWN_C {
            get {
                return ((bool)(this["U_B_Control_DOWN_C"]));
            }
            set {
                this["U_B_Control_DOWN_C"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool U_B_Control_DOWN_D {
            get {
                return ((bool)(this["U_B_Control_DOWN_D"]));
            }
            set {
                this["U_B_Control_DOWN_D"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool U_B_Control_LEFT_A {
            get {
                return ((bool)(this["U_B_Control_LEFT_A"]));
            }
            set {
                this["U_B_Control_LEFT_A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool U_B_Control_LEFT_B {
            get {
                return ((bool)(this["U_B_Control_LEFT_B"]));
            }
            set {
                this["U_B_Control_LEFT_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool U_B_Control_LEFT_C {
            get {
                return ((bool)(this["U_B_Control_LEFT_C"]));
            }
            set {
                this["U_B_Control_LEFT_C"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool U_B_Control_LEFT_D {
            get {
                return ((bool)(this["U_B_Control_LEFT_D"]));
            }
            set {
                this["U_B_Control_LEFT_D"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool U_B_Control_RIGHT_A {
            get {
                return ((bool)(this["U_B_Control_RIGHT_A"]));
            }
            set {
                this["U_B_Control_RIGHT_A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool U_B_Control_RIGHT_B {
            get {
                return ((bool)(this["U_B_Control_RIGHT_B"]));
            }
            set {
                this["U_B_Control_RIGHT_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool U_B_Control_RIGHT_C {
            get {
                return ((bool)(this["U_B_Control_RIGHT_C"]));
            }
            set {
                this["U_B_Control_RIGHT_C"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool U_B_Control_RIGHT_D {
            get {
                return ((bool)(this["U_B_Control_RIGHT_D"]));
            }
            set {
                this["U_B_Control_RIGHT_D"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool W_Control_UP_A {
            get {
                return ((bool)(this["W_Control_UP_A"]));
            }
            set {
                this["W_Control_UP_A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool W_Control_UP_B {
            get {
                return ((bool)(this["W_Control_UP_B"]));
            }
            set {
                this["W_Control_UP_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool W_Control_UP_C {
            get {
                return ((bool)(this["W_Control_UP_C"]));
            }
            set {
                this["W_Control_UP_C"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool W_Control_UP_D {
            get {
                return ((bool)(this["W_Control_UP_D"]));
            }
            set {
                this["W_Control_UP_D"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool W_Control_DOWN_A {
            get {
                return ((bool)(this["W_Control_DOWN_A"]));
            }
            set {
                this["W_Control_DOWN_A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool W_Control_DOWN_B {
            get {
                return ((bool)(this["W_Control_DOWN_B"]));
            }
            set {
                this["W_Control_DOWN_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool W_Control_DOWN_C {
            get {
                return ((bool)(this["W_Control_DOWN_C"]));
            }
            set {
                this["W_Control_DOWN_C"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool W_Control_DOWN_D {
            get {
                return ((bool)(this["W_Control_DOWN_D"]));
            }
            set {
                this["W_Control_DOWN_D"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool W_Control_LEFT_A {
            get {
                return ((bool)(this["W_Control_LEFT_A"]));
            }
            set {
                this["W_Control_LEFT_A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool W_Control_LEFT_B {
            get {
                return ((bool)(this["W_Control_LEFT_B"]));
            }
            set {
                this["W_Control_LEFT_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool W_Control_LEFT_C {
            get {
                return ((bool)(this["W_Control_LEFT_C"]));
            }
            set {
                this["W_Control_LEFT_C"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool W_Control_LEFT_D {
            get {
                return ((bool)(this["W_Control_LEFT_D"]));
            }
            set {
                this["W_Control_LEFT_D"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool W_Control_RIGHT_A {
            get {
                return ((bool)(this["W_Control_RIGHT_A"]));
            }
            set {
                this["W_Control_RIGHT_A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool W_Control_RIGHT_B {
            get {
                return ((bool)(this["W_Control_RIGHT_B"]));
            }
            set {
                this["W_Control_RIGHT_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool W_Control_RIGHT_C {
            get {
                return ((bool)(this["W_Control_RIGHT_C"]));
            }
            set {
                this["W_Control_RIGHT_C"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool W_Control_RIGHT_D {
            get {
                return ((bool)(this["W_Control_RIGHT_D"]));
            }
            set {
                this["W_Control_RIGHT_D"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int W_ControlSpeed_UP {
            get {
                return ((int)(this["W_ControlSpeed_UP"]));
            }
            set {
                this["W_ControlSpeed_UP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int W_ControlSpeed_DOWN {
            get {
                return ((int)(this["W_ControlSpeed_DOWN"]));
            }
            set {
                this["W_ControlSpeed_DOWN"] = value;
            }
        }
    }
}
